#!/bin/bash
echo "ALX"
*c
^C
*C
cd ..
*C

root@a9e0e889f02a:/alx-pre_course/0x01-git/bash# cat > school
#!/bin/bash
echo "School"
*C
root@a9e0e889f02a:/alx-pre_course/0x01-git/bash# git add .
root@a9e0e889f02a:/alx-pre_course/0x01-git/bash# git commit -m “Starting to code today, so cool”






[D[D[[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C










